CREATE TABLE MASSAPP.PERSON
(
	ID                     	    BIGSERIAL NOT NULL,
	MSISDN					    CHARACTER VARYING(50) NOT NULL UNIQUE,
	EMAIL					    CHARACTER VARYING(100) NOT NULL UNIQUE,
	NAME					    CHARACTER VARYING(50) NOT NULL,
	LAST_NAME					CHARACTER VARYING(50) NOT NULL,
	CREATED_AT				    TIMESTAMP NOT NULL,
	UPDATED_AT				    TIMESTAMP,
	MASSAGE_COUNT				INTEGER  DEFAULT 0,
	CONSTRAINT PERSON_PK PRIMARY KEY ( ID )
);

CREATE TABLE MASSAPP.MASSAGE_SESSION
(
	ID                     	    BIGSERIAL NOT NULL,
	DATE				    	TIMESTAMP NOT NULL,
	CONSTRAINT MASSAGE_SESSION_PK PRIMARY KEY ( ID )
);


CREATE TABLE MASSAPP.MASSAGE
(
	ID                     	    BIGSERIAL NOT NULL,
	PERSON_ID				    BIGSERIAL NOT NULL,
	SESSION_ID					BIGSERIAL NOT NULL,
	DATE				    	TIMESTAMP NOT NULL,
	CONSTRAINT MASSAGE_PK PRIMARY KEY ( ID )
);

ALTER TABLE MASSAPP.MASSAGE ADD CONSTRAIN MASSAGE_SESSION_FK01 FOREIGN KEY (MASSAGE_SESSION_ID) REFERENCES MASSAPP.MASSAGE_SESSION (ID);
ALTER TABLE MASSAPP.MASSAGE ADD CONSTRAIN PERSON_FK01 FOREIGN KEY (PERSON_ID) REFERENCES MASSAPP.PERSON (ID);


